[package]
name = "isophes/nuclear"
description = "Fast, Light, Adaptable, Easy. Everything that frameworks should be."
version = "1.0.0"
licence = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
