name: MkDocs Deploy
on:
  push:
    branches:
      - main

env:
  NUCLEAR_VERSION: 0.1
  NUCLEAR_DEPLOY_TYPE: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install setuptools (for mike)
        run: pip install --upgrade setuptools

      - name: Install MkDocs
        run: pip install mkdocs-material==8.2.13

      - name: Install mike
        run: pip install mike==1.1.2

      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages --depth=1

      - name: Deploy latest documentation
        if: env.NUCLEAR_DEPLOY_TYPE == 'release'
        run: mike deploy $NUCLEAR_VERSION latest -u -b gh-pages

      - name: Set default version to latest
        if: env.NUCLEAR_DEPLOY_TYPE == 'release'
        run: mike set-default latest -b gh-pages -p

      - name: Deploy developer documentation
        if: env.NUCLEAR_DEPLOY_TYPE == 'dev'
        run: mike deploy $NUCLEAR_VERSION -u -b gh-pages -p